# Generated by Django 4.1.3 on 2023-03-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='sana',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
